# Document:
# http://simiki.org/docs/configuration.html

url: wiki.holten.site
title: wiki·holten
keywords: wiki,holten
description: holten's wiki.
author: holten

root: /
source: content
destination: output
themes_dir: themes
theme: yasimple_x2

default_ext: md
pygments: true
debug: false